-- using SHOW INDEX:
SHOW INDEX FROM TableName FROM DatabaseName

-- using INFORMATION_SCHEMA.STATISTICS table:
SELECT 
    TABLE_NAME
    ,INDEX_NAME
    ,SEQ_IN_INDEX
    ,COLUMN_NAME
    ,CARDINALITY
    ,INDEX_TYPE    
FROM INFORMATION_SCHEMA.STATISTICS 
WHERE table_schema = 'DatabaseName' 